# CORE
#

# Reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Passthrough dla obrazów (WezTerm/vifm inline previews)
set -g allow-passthrough on

# Tryb vi w copy-mode
setw -g mode-keys vi

# Szybka reakcja na ESC (Vim w tmux)
set -s escape-time 0

# Historia, powtórzenia, message timeout
set -g history-limit 50000
set -g repeat-time 100
set -g display-time 1500

# Mysz
set -g mouse on

# Nazwy okien niech nie skaczą
set -g allow-rename off
setw -g automatic-rename off

# Focus-events (użyteczne dla edytorów)
set -g focus-events on

# Agresywne dopasowanie rozmiaru okna (multi-monitor)
setw -g aggressive-resize on

# Prefix na C-a i kompatybilność
unbind C-b
set -g prefix C-a
bind C-a send-prefix

