# KEYS
#

# Ruch jak w Vim
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Splity
bind v split-window -v
bind b split-window -h

# Resize
bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

# Przerzucanie okien
bind -n C-S-Left  swap-window -t -1
bind -n C-S-Right swap-window -t +1

# Sync panes (on/off)
bind -r p setw synchronize-panes

# Respawn bieżącej pany
bind q respawn-pane -k

