# COPY - PASTE
#

# Copy-mode start
bind [ copy-mode

# Selekcja i kopiowanie w stylu Vim
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Przewijanie w copy-mode (opcjonalnie)
bind -T copy-mode-vi PageUp   send-keys -X page-up
bind -T copy-mode-vi PageDown send-keys -X page-down
bind -T copy-mode-vi S-PageUp   send-keys -X halfpage-up
bind -T copy-mode-vi S-PageDown send-keys -X halfpage-down

# Mac: wklej ze schowka systemowego
bind P run-shell "pbpaste | tmux load-buffer - \; paste-buffer"

