# COPY - PASTE
#

# Copy-mode start
bind [ copy-mode

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P run-shell "pbpaste | tmux load-buffer - \; paste-buffer"

# Przewijanie w copy-mode
bind -T copy-mode-vi PageUp   send-keys -X page-up
bind -T copy-mode-vi PageDown send-keys -X page-down
bind -T copy-mode-vi S-PageUp   send-keys -X halfpage-up
bind -T copy-mode-vi S-PageDown send-keys -X halfpage-down
