# PLUGINS
#

# --- Lista pluginów ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-logging'

# Bateria
set -g @plugin 'tmux-plugins/tmux-battery'

# URL-e
set -g @plugin 'tmux-plugins/tmux-urlview'

# Schowek
set -g @plugin 'tmux-plugins/tmux-yank'

# Sesje: resurrect + continuum
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'
# (opcjonalnie ścieżki backupów)
# set -g @resurrect-dir '~/.local/share/tmux/resurrect'

