# THEME
#

# Truecolor + kształt kursora (bez duplikatów w innych modułach)
# Blokowy kursor w tmux
# 0 reset do domyślnego
# 1 blinking block
# 2 steady block (stały blok)
# 3 blinking underline
# 4 steady underline
# 5 blinking bar
# 6 steady bar (beam)
set -g default-terminal "tmux-256color"
set -as terminal-features 'tmux-256color:RGB'

# (opcjonalnie) zewnętrzny motyw — jeśli używasz tmux-termed
if-shell "[ -r ~/.tmux/themes/tmux-termed/termed.tmux ]" \
  "source-file ~/.tmux/themes/tmux-termed/termed.tmux"

# Nasz motyw (nadpisze kolory, zachowa układ jeśli termed coś zmienia)
source-file ~/.tmux/themes/vscode-dark-modern.tmux
