# -------- ~/.tmux.conf --------

# Shell
set -g default-shell "/bin/zsh"

# Podstawowe ustawienia
source-file ~/.tmux/modules/00-core.conf

# Klawisze, podziały, nawigacja
source-file ~/.tmux/modules/10-keys.conf

# Kopiowanie / schowek
source-file ~/.tmux/modules/20-copy-paste.conf

# Mysz
source-file ~/.tmux/modules/30-mouse.conf

# URL-view (jeśli chcesz)
source-file ~/.tmux/modules/40-urls.conf

# Pluginy (TPM i reszta)
source-file ~/.tmux/modules/50-plugins.conf

# Motyw + pasek
source-file ~/.tmux/modules/60-theme.conf

# Ewentualnie: konfiguracja zdalna
# source-file ~/.tmux/modules/90-remote.conf

# TPM na samym końcu
run -b '~/.tmux/plugins/tpm/tpm'
