# ~/.config/yazi.toml

[mgr]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
case_sensitive = false

# Opcjonalnie: wielkość podglądu
# [preview]
# max_width = 800
# max_height = 600

[opener]
# Default
open = [
  # macOS
  { run = 'open "$0"', for = "macos", orphan = true },
]

preview-vid = [
  { run = 'open -a VLC "$0"',  for = "macos", orphan = true },
]

preview-pic = [
  { run = 'open -a Preview "$0"',  for = "macos", orphan = true },
]

[[open.rules]]
mime = "image/*"
use  = "preview-pic"

[[open.rules]]
mime = "video/*"
use  = "preview-vid"

[[manager.prepend_cmd]]
name = "v"
run  = 'shell --block -- echo "$@"'
desc = "Open in vim"
