[Glade Windows]
main-x=10
main-y=25
main-width=944
main-height=607
main-maximized=true

[center_pane]
position=2649

[left_pane]
position=439

[Preferences]
catalog-paths=

[Load and Save]
backup=true
autosave=true
autosave-seconds=5

[Save Warnings]
versioning=true
deprecations=false
unrecognized=true
