[Qt]
style=GTK+

[Qt%20Plugin%20Cache%204.8.false]
usr\lib\qt\plugins\inputmethods\libqimsw-multi.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\keepassx\libkeepassx-autotype-x11.so=40807, 0, x86_64 linux g++-6.3.0 full-config, 2017-06-01T07:16:57
usr\lib\qt\plugins\iconengines\libqsvgicon.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqgif.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqico.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqjpeg.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqmng.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqsvg.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqtga.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56
usr\lib\qt\plugins\imageformats\libqtiff.so=40807, 0, x86_64 linux g++-8.3.0 full-config, 2019-06-13T08:21:56

[Qt%20Factory%20Cache%204.8]
com.trolltech.Qt.QInputContextFactoryInterface%3A\usr\lib\qt\plugins\inputmethods\libqimsw-multi.so=2019-06-13T08:21:56, imsw-multi
com.trolltech.Qt.QIconEngineFactoryInterfaceV2%3A\usr\lib\qt\plugins\iconengines\libqsvgicon.so=2019-06-13T08:21:56, svg, svgz, svg.gz
com.trolltech.Qt.QIconEngineFactoryInterface%3A\usr\lib\qt\plugins\iconengines\libqsvgicon.so=2019-06-13T08:21:56
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqgif.so=2019-06-13T08:21:56, gif
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqico.so=2019-06-13T08:21:56, ico
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqjpeg.so=2019-06-13T08:21:56, jpeg, jpg
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqmng.so=2019-06-13T08:21:56, mng
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqsvg.so=2019-06-13T08:21:56, svg, svgz
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqtga.so=2019-06-13T08:21:56, tga
com.trolltech.Qt.QImageIOHandlerFactoryInterface%3A\usr\lib\qt\plugins\imageformats\libqtiff.so=2019-06-13T08:21:56, tiff, tif
